### ISSUE TITLE
Failed to build with Android Studio 3.3

### ISSUE THREAD

**Issue by olliwang** [forexample/android-studio-with-hunter#1]
This project does not work with Android Studio 3.3, which switches to `clang` and uses system's `ld` for linking. Any idea how to fix it? Thanks.

        Error configuring CMake server (/Users/usr/Library/Android/sdk/cmake/3.10.2.4988404/bin).
    [hunter *** DEBUG *** 2019-02-25T16:38:08] HUNTER_ROOT set using HOME environment variable
    [hunter *** DEBUG *** 2019-02-25T16:38:08] HUNTER_ROOT: /Users/usr/.hunter
    [hunter *** DEBUG *** 2019-02-25T16:38:08] Settings (initialize):
    [hunter *** DEBUG *** 2019-02-25T16:38:08]   HunterGate done (NO)
    [hunter *** DEBUG *** 2019-02-25T16:38:08]   Cache init (NO)
    Android: Targeting API '24' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
    Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
    Check for working C compiler: /Users/usr/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
    Check for working C compiler: /Users/usr/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- broken
    CMake Error at /Users/usr/Library/Android/sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler

        "/Users/usr/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"

      is not able to compile a simple test program.

      It fails with the following output:

        Change Dir: /Users/usr/Downloads/android-studio-with-hunter-master/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeTmp
    
        Run Build Command:"/Users/usr/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja" "cmTC_d3546"
        [1/2] Building C object CMakeFiles/cmTC_d3546.dir/testCCompiler.c.o
        [2/2] Linking C executable cmTC_d3546
        FAILED: cmTC_d3546 
        : && /Users/usr/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android24 --gcc-toolchain=/Users/usr/Library/Android/sdk/ndk-bundle/toolchains//prebuilt/darwin-x86_64 --sysroot=/Users/usr/Library/Android/sdk/ndk-bundle/sysroot -isystem /Users/usr/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /Users/usr/Library/Android/sdk/ndk-bundle/platforms/android-24/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/Users/usr/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fpie CMakeFiles/cmTC_d3546.dir/testCCompiler.c.o  -o cmTC_d3546  -latomic -lm && :

        ld: unknown option: --sysroot=/Users/usr/Library/Android/sdk/ndk-bundle/platforms/android-24/arch-arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.

Android Studio 3.3 with default NDK r19, CMake 3.10.2, and Grade 4.10.1.

**Comment by ruslo** [comment]
> NDK r19

It's not supported by CMake builtin modules (which is a requirement). Workaround is to switch to NDK r18, see:
- https://gitlab.kitware.com/cmake/cmake/issues/18739

**Comment by olliwang** [comment]
Thanks, @ruslo. Should I downgrade Android Studio back to 3.2? I tried to downgrade NDK to r18, but still got a ninja build error. 

    [0/11] Performing build step for 'yaml-cpp-Release'
    ninja: error: build.ninja:326: bad $-escape (literal $ must be written as $$)

    FAILED: yaml-cpp-Release-prefix/src/yaml-cpp-Release-stamp/yaml-cpp-Release-build 
    cd /Users/olliwang/.hunter/_Base/712b3f5/4e02b95/19a190d/Build/yaml-cpp/Build/yaml-cpp-Release-prefix/src/yaml-cpp-Release-build && /Users/olliwang/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake --build . --config Release -- -j8 && /Users/olliwang/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake -E touch /Users/olliwang/.hunter/_Base/712b3f5/4e02b95/19a190d/Build/yaml-cpp/Build/yaml-cpp-Release-prefix/src/yaml-cpp-Release-stamp/yaml-cpp-Release-build
    ninja: build stopped: subcommand failed.

It seems the variable style is wrong. Not sure what causes this.

**Comment by ruslo** [comment]
> `[0/11] Performing build step for 'yaml-cpp-Release'`

`yaml-cpp` package is not a part of this example and is not a dependency of `md5`. Have you modified this example?

**Comment by olliwang** [comment]
Sorry, I forgot to mention that the previous error was generated by my own demo (which uses only yaml-cpp).

**Comment by ruslo** [comment]
If there are no problems with the original example with md5 package please close this issue.

**Comment by olliwang** [comment]
Sorry I didn't notice that it's the yaml-cpp package's issue.
