### ISSUE TITLE
Android: NDK r19 (and above) support

### ISSUE THREAD

**Issue by Bjoe** [forexample/android-studio-with-hunter#2]
Hi,

I get in the same issue like on #1 
I know that there is an cmake issue https://gitlab.kitware.com/cmake/cmake/issues/18739 about NDK r19 support.

The problem is here:
https://github.com/forexample/android-studio-with-hunter/blob/f8c19c54dc949c8ceacb0a768a88683ad948a9bc/cmake/template/toolchain.cmake.in#L88
If we set this `CMAKE_SYSTEM_VERISON` to `${ANDROID_NATIVE_API_LEVEL}`, we use the cmake builtin support for android and set the NDK environment. You should set this to `1` (This is also what the android toolchain did). The android toolchain provided by the NDK is **"now"** proper set the NDK environment for cmake. This is also a goal of the android NDK, from the NDK roadmap:
>
> We will reorganize our toolchain file to match the typical implementation of a CMake platform integration (like $CMAKE/Modules/Platform/Android-*.cmake) and CMake will be modified to load the implementation from the NDK rather than its own.

See NDK roadmap: https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#cmake

There is also a discussion on cmake to remove CMake builtin support for android: https://gitlab.kitware.com/cmake/cmake/issues/18787

So I think we can remove to set `CMAKE_SYSTEM_VERISON` or add a check if NDK is higher then "xyz" and cmake version is higher then xyz ... (I use cmake version 3.11.4)
and tweak following CMake Android variables
<pre>
set(CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE "${CMAKE_LIBRARY_ARCHITECTURE}")
set(CMAKE_C_ANDROID_TOOLCHAIN_PREFIX "${ANDROID_TOOLCHAIN_PREFIX}")
set(CMAKE_C_ANDROID_TOOLCHAIN_SUFFIX "${ANDROID_TOOLCHAIN_SUFFIX}")
</pre>

This works for me, but I'm also interesting if it works for "you" guys ... then I will create a android ndk bug report, to set these cmake android variables.

**Update**: For the NDK r16 `set(CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE "${ANDROID_HEADER_TRIPLE}")` should be used. For NDK r20 `set(CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE "${CMAKE_LIBRARY_ARCHITECTURE}")` is the correct one.

**Comment by Bjoe** [comment]
Btw. you can also use this approach for the NDK version 16 .... but then you need to tweak additional CMake Android variables:

<pre>
list(APPEND CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_SYSROOT}/usr/include" "${CMAKE_SYSROOT}/usr/include/${ANDROID_HEADER_TRIPLE}")
list(APPEND CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${CMAKE_SYSROOT}/usr/include" "${CMAKE_SYSROOT}/usr/include/${ANDROID_HEADER_TRIPLE}")
</pre>

**Comment by ruslo** [comment]
> There is also a discussion on cmake to remove CMake builtin support for android: https://gitlab.kitware.com/cmake/cmake/issues/18787

The issue is still opened, I don't think it's a good idea to take action before they decide what the future of `ANDROID_*` variables is.

- https://github.com/android-ndk/ndk/issues/463#issuecomment-456576852
- https://gitlab.kitware.com/cmake/cmake/issues/18787#note_520775

**Comment by Bjoe** [comment]
I fully understand your point to wait and I even don't like my idea to add some "version" checks :-)

But maybe there is another solution (create a hint or doc. entry) because for me I lost three days to find out what are the problem in my build and find a solution for that. I would like to use the new NDK with hunter because of the new C++ features :-).

I created also a feature request about the [missing cmake variables in the toolchain file](https://github.com/android-ndk/ndk/issues/1012). 

Again, for me the solution that I did works and maybe somebody else in the C++ community/world would also like to use the new C++ feature for android with hunter.

I really hope and wish (and that's not only me) that the cmake and NDK project find **together** a proper solution ...

**Comment by ruslo** [comment]
> But maybe there is another solution (create a hint or doc. entry)

There is already a note in the documentation that NDK r19 is not working and links to the upstream issues. If you prepare some repository or post an article in the blog, then we can add a **link** not more.

> I really hope and wish (and that's not only me) that the cmake and NDK project find together a proper solution ...

I'm not the person who made this mess, and Hunter is not a source of the conflict and not a place to introduce fixes. Please discuss it with CMake and Android NDK developers.

**Comment by Bjoe** [comment]
I know that you are not the person who made this mess .... was only a "loud thinking" ;-)

But for the completeness: [DanAlbert wrote](https://github.com/android-ndk/ndk/issues/1012#issuecomment-505284837):
> For the time being, the toolchain file is your best bet when using a new NDK. Upstream takes some time to adapt. Like the roadmap and the other bug says, we'll be resolving this soon (unfortunately it's only "soon" in the sense that it's only one or two items down the roadmap; it'll be a several months to a year before this is actually complete).

With toolchain file, he means the toolchain file in the NDK.

And also they will add the missing:
`CMAKE_<LANG>_ANDROID_TOOLCHAIN_MACHINE`
`CMAKE_<LANG>_ANDROID_TOOLCHAIN_PREFIX`
`CMAKE_<LANG>_ANDROID_TOOLCHAIN_SUFFIX`

in the android [ndk r21](https://github.com/android-ndk/ndk/issues/1012#event-2436272604)

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
